[project]
name = "calculatortyper"
version = "0.1.0"
description = "Simple CLI calculator using python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=13.8.1",
    "typer>=0.12.5",
]
